### ISSUE TITLE
How to add a click event?

### ISSUE THREAD

**Issue by o1exij** [thclark/cpplot-viewer#5]
I am using SurfacePlot like this:

```
      Figure fig = Figure();
      SurfacePlot p = SurfacePlot();

      int height = granularity;
      int width = granularity;

      p.x = Eigen::RowVectorXd::LinSpaced(width, transformation_steps[0].minK, transformation_steps[0].maxK).replicate(height, 1).array();
      p.y = Eigen::VectorXd::LinSpaced(height, transformation_steps[1].minK, transformation_steps[1].maxK).replicate(1, width).array();
      p.z = Eigen::ArrayXXd(width, height);

      for(int i=0; i<granularity; i++) {
        for(int j=0; j<granularity; j++) {
          p.z(i, j) = (transformation_step_outputs(0, i)+transformation_step_outputs(1, j)+mean_value)* scaling_vector(scaling_vector.size()-1);
        }
      }
      fig.add(p);

```
How can I add a click event which returns me p.x and p.y?

**Comment by thclark** [comment]
Hi @o1exij thanks for using cpplot :)

You can't add click events from the C++ side unfortunately The C++ lib is just there to help you generate correctly structured JSON that's plotly compatible, there's no way of compiling callbacks in C++ that then get executed in the javascript runtime.

Although that would be an ultra-cool feature, that'd require some truly mad skills with webassembly (if even possible at all!!).

However, you can fork this cpplot-viewer project (or just use its fragments of code as an example), then modify your javascript to add a callback to the click event [as is shown in "Binding to Click Events" in the plotly docs](https://plotly.com/javascript/click-events/#binding-to-click-events), which would return your `p.x` and your `p.y`.

Good luck!

**Comment by o1exij** [comment]
`From ae509765e6537ca908069a43eeef6223a3d587a5 Mon Sep 17 00:00:00 2001
From: Olexij Tkatchenko <olexij@tkatchenko.com>
Date: Wed, 6 Jan 2021 15:51:13 +0100
Subject: [PATCH] Added onClick() handling to FigureViewer. The handling is
 context specific, currently it only logs the click coordinates

---
 src/components/Figures/FigureViewer/FigureViewer.js | 5 +++++
 1 file changed, 5 insertions(+)

diff --git a/src/components/Figures/FigureViewer/FigureViewer.js b/src/components/Figures/FigureViewer/FigureViewer.js
index 57643c6..ad0766d 100644
--- a/src/components/Figures/FigureViewer/FigureViewer.js
+++ b/src/components/Figures/FigureViewer/FigureViewer.js
@@ -141,6 +141,10 @@ class FigureBase extends Component {
     this.setState(figure)
   }

+  onClick(figure) {
+    console.log('You clicked on '+figure.points[0]['x'].toString()+' '+figure.points[0]['y'].toString()+' '+figure.points[0]['z'].toString());
+  }
+
   render() {
     if (this.props.detail) {
       return (
@@ -151,6 +155,7 @@ class FigureBase extends Component {
           config={this.state.config}
           onInitialized={(figure) => this.setStateOnFigureInitialized(figure)}
           onUpdate={(figure) => this.setStateOnFigureUpdate(figure)}
+          onClick={(figure) => this.onClick(figure)}
           style={{ width: '100%', height: '100%' }}
           useResizeHandler
         />
--
2.22.0
`
